name: Docker Prod

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v2 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1  

      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
        
      - name: Test printing your secret (Remove this step in production)
        run: |
          cat ./.env

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.DOCKER_USER }}/decrypt-gpg:test

      - name: Run unit tests
        run: |
          docker run --rm $DOCKER_USER/decrypt-gpg:test sh run_tests.sh

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_USER }}/decrypt-gpg:latest   
